export const data = [
  {
    "Name": "Lulu Berry",
    "Sex": "F",
    "Overlap": "100%",
    "Overlap_score": 1,
    "Age": 90,
    "Age_score": 1,
    "Relation": "You",
    "Relation_score": 1,
    "Distance": 10,
    "Distance_score": 1,
    "Total_Contribution": 10000000
  },
  {
    "Name": "Elijah Berry",
    "Sex": "M",
    "Overlap": "80%",
    "Overlap_score": 2,
    "Age": 63,
    "Age_score": 2,
    "Relation": "Brother",
    "Relation_score": 2,
    "Distance": 20,
    "Distance_score": 2,
    "Total_Contribution": 7000000
  },
  {
    "Name": "Julia Berry Richards",
    "Sex": "F",
    "Overlap": "50%",
    "Overlap_score": 3,
    "Age": 32,
    "Age_score": 4,
    "Relation": "Granddaughter",
    "Relation_score": 4,
    "Distance": 40,
    "Distance_score": 4,
    "Total_Contribution": 4500000
  },
  {
    "Name": "Columbus Richards",
    "Sex": "M",
    "Overlap": "20%",
    "Overlap_score": 5,
    "Age": 8,
    "Age_score": 5,
    "Relation": "Great Grandson",
    "Relation_score": 5,
    "Distance": 50,
    "Distance_score": 5,
    "Total_Contribution": 2000000
  },
  {
    "Name": "Millie Richards",
    "Sex": "F",
    "Overlap": "2%",
    "Overlap_score": 5,
    "Age": 4,
    "Age_score": 5,
    "Relation": "Great Granddaughter",
    "Relation_score": 5,
    "Distance": 50,
    "Distance_score": 5,
    "Total_Contribution": 1000000
  },
  {
    "Name": "Harrison Berry",
    "Sex": "M",
    "Overlap": "30%",
    "Overlap_score": 4,
    "Age": 59,
    "Age_score": 2,
    "Relation": "Son",
    "Relation_score": 2,
    "Distance": 20,
    "Distance_score": 2,
    "Total_Contribution": 5000000
  },
  {
    "Name": "Katharine Berry Silva",
    "Sex": "F",
    "Overlap": "40%",
    "Overlap_score": 4,
    "Age": 33,
    "Age_score": 2,
    "Relation": "Daughter",
    "Relation_score": 2,
    "Distance": 20,
    "Distance_score": 2,
    "Total_Contribution": 3000000
  },
  {
    "Name": "Hulda Silva",
    "Sex": "F",
    "Overlap": "0%",
    "Overlap_score": 5,
    "Age": 3,
    "Age_score": 5,
    "Relation": "Great Grandson",
    "Relation_score": 5,
    "Distance": 50,
    "Distance_score": 5,
    "Total_Contribution": 150000
  },
  {
    "Name": "Jackson Berry",
    "Sex": "M",
    "Overlap": "90%",
    "Overlap_score": 1,
    "Age": 30,
    "Age_score": 4,
    "Relation": "Son",
    "Relation_score": 2,
    "Distance": 20,
    "Distance_score": 2,
    "Total_Contribution": 5000000
  },
  {
    "Name": "Austin Berry",
    "Sex": "M",
    "Overlap": "88%",
    "Overlap_score": 1,
    "Age": 25,
    "Age_score": 4,
    "Relation": "Cousin",
    "Relation_score": 3,
    "Distance": 30,
    "Distance_score": 3,
    "Total_Contribution": 2500000
  },
  {
    "Name": "Benjamin Berry",
    "Sex": "M",
    "Overlap": "35%",
    "Overlap_score": 4,
    "Age": 4,
    "Age_score": 2,
    "Relation": "Brother-in-law",
    "Relation_score": 3,
    "Distance": 30,
    "Distance_score": 3,
    "Total_Contribution": 100000
  },
  {
    "Name": "Amanda Berry Spencer",
    "Sex": "F",
    "Overlap": "66%",
    "Overlap_score": 2,
    "Age": 57,
    "Age_score": 2,
    "Relation": "Sister",
    "Relation_score": 2,
    "Distance": 20,
    "Distance_score": 2,
    "Total_Contribution": 8000000
  },
  {
    "Name": "Lee Spencer",
    "Sex": "M",
    "Overlap": "20%",
    "Overlap_score": 5,
    "Age": 26,
    "Age_score": 4,
    "Relation": "Son in Law",
    "Relation_score": 3,
    "Distance": 30,
    "Distance_score": 3,
    "Total_Contribution": 1500000
  },
  {
    "Name": "Sylvester Spencer",
    "Sex": "M",
    "Overlap": "33%",
    "Overlap_score": 4,
    "Age": 24,
    "Age_score": 4,
    "Relation": "Grandson",
    "Relation_score": 4,
    "Distance": 40,
    "Distance_score": 4,
    "Total_Contribution": 250000
  }
]